name = "AAF Functions"
prefix = "aaf"
author = "AAF"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "LICENSE",
    "meta.cpp",
]

[version]
git_hash = 0

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3
]

[hemtt.launch.spe]
workshop = [
    "450814997", # CBA_A3
]
dlc = [
    "spe"
]

[hemtt.launch.vn]
workshop = [
    "450814997", # CBA_A3's Workshop ID
]
dlc = [
    "S.O.G. Prairie Fire",
]

[hemtt.launch.ws]
workshop = [
    "450814997", # CBA_A3's Workshop ID
]
dlc = [
    "Western Sahara",
]

[hemtt.launch.rhs]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "843425103", # RHS AFRF Workshop ID
    "843577117", # RHS USAF Workshop ID
    "843593391", # RHS GREF Workshop ID
    "843632231", # RHS SAF  Workshop ID
]
