name = "AAF Functions"
prefix = "aaf"
author = "AAF"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "LICENSE",
    "meta.cpp",
]

[version]
git_hash = 0


[hemtt.launch.default]
presets = ["Arma_3_Preset_AAF_Modern"]
