name = "AAF Functions"
prefix = "aaf"
author = "AAF"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "LICENSE",
    "meta.cpp",
]

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[hemtt.launch.default]
parameters = ["-noSplash", "-skipIntro"]
presets = ["Arma 3 Preset AAF Core Dev 29JUL24.html"]

[hemtt.launch.spe]
workshop = [
    "450814997", # CBA_A3
]
dlc = [
    "spe"
]

[hemtt.launch.vn]
workshop = [
    "450814997", # CBA_A3's Workshop ID
]
dlc = [
    "S.O.G. Prairie Fire",
]

[hemtt.launch.ws]
workshop = [
    "450814997", # CBA_A3's Workshop ID
]
dlc = [
    "Western Sahara",
]

